name: Deploy

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        npm install
    - name: deploy to firbase
      run: |
        ./node_modules/.bin/firebase deploy --project=tokuda-playground-gh-actions --token=${{ secrets.FIREBASE_TOKEN }}
